<?xml version="1.0" encoding="UTF-8"?><testrun name="BucketSortTest" project="test.challenge.algorithm" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="test.root.BucketSortTest" time="0.003">
    <testcase name="testSort" classname="test.root.BucketSortTest" time="0.003">
      <failure>java.lang.AssertionError: Positions &lt;1,2&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at test.root.BucketSortTest.testSort(BucketSortTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)

</failure>
    </testcase>
  </testsuite>
</testrun>
